/*
 * OneOf
 *
 * OneOf
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing BookShopInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BookShopInfoTests
    {
        // TODO uncomment below to declare an instance variable for BookShopInfo
        //private BookShopInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BookShopInfo
            //instance = new BookShopInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BookShopInfo
        /// </summary>
        [Test]
        public void BookShopInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" BookShopInfo
            //Assert.IsInstanceOf(typeof(BookShopInfo), instance);
        }


        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Test]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'Genres'
        /// </summary>
        [Test]
        public void GenresTest()
        {
            // TODO unit test for the property 'Genres'
        }

    }

}
