<?php

/**
 * DefaultApiTest
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Security
 *
 * Security
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\DefaultApi;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\DefaultApi
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for basicGet
     *
     * .
     *
     * @covers ::basicGet
     */
    public function testBasicGet()
    {
    }

    /**
     * Test case for bearerGet
     *
     * .
     *
     * @covers ::bearerGet
     */
    public function testBearerGet()
    {
    }

    /**
     * Test case for multipleGet
     *
     * .
     *
     * @covers ::multipleGet
     */
    public function testMultipleGet()
    {
    }

    /**
     * Test case for oauth2Get
     *
     * .
     *
     * @covers ::oauth2Get
     */
    public function testOauth2Get()
    {
    }
}
