<?php
/**
 * ShopListResult
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * OneOf
 *
 * OneOf
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the ShopListResult model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class ShopListResult 
{
        /**
     * @var OpenAPI\Server\Model\Shop[]|null
     * @SerializedName("data")
     * @Assert\All({
     *   @Assert\Type("OpenAPI\Server\Model\Shop")
     * })
     * @Type("array<OpenAPI\Server\Model\Shop>")
     */
    protected $data;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->data = isset($data['data']) ? $data['data'] : null;
    }

    /**
     * Gets data.
     *
     * @return OpenAPI\Server\Model\Shop[]|null
     */
    public function getData(): ?array
    {
        return $this->data;
    }

    /**
     * Sets data.
     *
     * @param OpenAPI\Server\Model\Shop[]|null $data
     *
     * @return $this
     */
    public function setData(array $data = null)
    {
        $this->data = $data;

        return $this;
    }
}


