<?php
/**
 * Shop
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * OneOf
 *
 * OneOf
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Shop model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class Shop 
{
        /**
     * @var string|null
     * @SerializedName("id")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $id;

    /**
     * @var OpenAPI\Server\Model\ShopInfo|null
     * @SerializedName("info")
     * @Assert\Type("OpenAPI\Server\Model\ShopInfo")
     * @Type("OpenAPI\Server\Model\ShopInfo")
     */
    protected $info;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->id = isset($data['id']) ? $data['id'] : null;
        $this->info = isset($data['info']) ? $data['info'] : null;
    }

    /**
     * Gets id.
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Sets id.
     *
     * @param string|null $id
     *
     * @return $this
     */
    public function setId($id = null)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets info.
     *
     * @return OpenAPI\Server\Model\ShopInfo|null
     */
    public function getInfo(): ?ShopInfo
    {
        return $this->info;
    }

    /**
     * Sets info.
     *
     * @param OpenAPI\Server\Model\ShopInfo|null $info
     *
     * @return $this
     */
    public function setInfo(ShopInfo $info = null)
    {
        $this->info = $info;

        return $this;
    }
}


