<?php

/**
 * Swagger Petstore - OpenAPI 3.0
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach! You can now help us improve the API whether it's by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.  _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_  Some useful links: - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore) - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 * The version of the OpenAPI document: 1.0.11
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\PetApi;

/**
 * PetApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\PetApi
 */
class PetApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addPet
     *
     * Add a new pet to the store.
     *
     * @covers ::addPet
     */
    public function testAddPet()
    {
        $this->markTestIncomplete(
            'Test of "addPet" method has not been implemented yet.'
        );
    }

    /**
     * Test case for deletePet
     *
     * Deletes a pet.
     *
     * @covers ::deletePet
     */
    public function testDeletePet()
    {
        $this->markTestIncomplete(
            'Test of "deletePet" method has not been implemented yet.'
        );
    }

    /**
     * Test case for findPetsByStatus
     *
     * Finds Pets by status.
     *
     * @covers ::findPetsByStatus
     */
    public function testFindPetsByStatus()
    {
        $this->markTestIncomplete(
            'Test of "findPetsByStatus" method has not been implemented yet.'
        );
    }

    /**
     * Test case for findPetsByTags
     *
     * Finds Pets by tags.
     *
     * @covers ::findPetsByTags
     */
    public function testFindPetsByTags()
    {
        $this->markTestIncomplete(
            'Test of "findPetsByTags" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getPetById
     *
     * Find pet by ID.
     *
     * @covers ::getPetById
     */
    public function testGetPetById()
    {
        $this->markTestIncomplete(
            'Test of "getPetById" method has not been implemented yet.'
        );
    }

    /**
     * Test case for updatePet
     *
     * Update an existing pet.
     *
     * @covers ::updatePet
     */
    public function testUpdatePet()
    {
        $this->markTestIncomplete(
            'Test of "updatePet" method has not been implemented yet.'
        );
    }

    /**
     * Test case for updatePetWithForm
     *
     * Updates a pet in the store with form data.
     *
     * @covers ::updatePetWithForm
     */
    public function testUpdatePetWithForm()
    {
        $this->markTestIncomplete(
            'Test of "updatePetWithForm" method has not been implemented yet.'
        );
    }

    /**
     * Test case for uploadFile
     *
     * uploads an image.
     *
     * @covers ::uploadFile
     */
    public function testUploadFile()
    {
        $this->markTestIncomplete(
            'Test of "uploadFile" method has not been implemented yet.'
        );
    }
}
